version: '3'
services:
    mongodb:
        image: mongo
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - C:/data/db:/data/db
        ports:
            - 27017:27017
        command: mongod

    test:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DBWEBB_DSN=mongodb://mongodb:27017/test
        links:
            - mongodb
        volumes:
            - ./:/home/node/app
